### ISSUE TITLE
Improve description

### ISSUE THREAD

**Issue by bullmastiffo** [bullmastiffo/homeassistant_tools#1]
suggestions:

If I can suggest just 1-2 small things for your documentation:
1, At step3, you have a line with only ‘ssh’, mkdir is missing from there
2, Also at step3, after ssh to the root user, please add a note if a successful login occurs, one must logout from the root account before continuing with the cp command
3, I don’t know if it a general behaviour for asus routers, or not, bot worth a note somewhere: if the router allows only one login at a time, the certificate download won’t be successful if there is an already existing active login. Which is most likely a valid condition, when one just obtained the authorization key, and left the browser as-is.

**Comment by owenk23** [comment]
Hey - was there any updated on getting this added. I appreciate the effort so far but I'm not as technical as some others. Thanks again!

**Comment by bullmastiffo** [comment]
Fixed in [commit](https://github.com/bullmastiffo/homeassistant_tools/commit/81f17ec80726f5832bc285976fe3d2e64537b4fe)
